---
title: WFH or WFK(D)?
author: masdian
date: '2020-03-20'
slug: wfh-or-wfk-d
categories: []
tags: []
lastmod: '2020-03-20T09:00:38+07:00'
layout: post
type: post
highlight: no
---

Sudah hampir satu minggu pemerintah menghimbau warga Indonesia agar Bekerja dari Rumah (*Work from Home*). Sampai hari ini sudah banyak instansi pemerintah dan swasta yang mengijinkan pegawainya untuk *Work from Home*. Akan tetapi, banyak juga yang masih ```ngeyel``` dan tetap seliweran dari rumah ke tempat kerja. Bagi yang berkerja di bidang produksi, kebijakan WFH sangat sukar untuk diterapkan selain dengan meliburkan total pekerja di bidang produksi atau tetap berproduksi seperti biasa. Sedangkan untuk pekerja yang bekerja di bidang non produksi, kebijakan WFH bisa dilaksanakan dengan mudah. Dengan bermodalkan koneksi internet, perangkat, dan kemauan, pekerjaan bisa tetap dilaksanakan meskipun dikerjakan di atas tempat tidur.

Kebetulan dua minggu lalu baru saja membeli laptop Lenovo Ideapad S340 Ryzen 5 3500 dengan RAM 12 GB dan SSD 512. Pembelian laptop ini tidak ada kaitannya dengan persiapan bekerja dari rumah dan pada saat membeli tidak kepikiran bakalan ada kebijakan WFH, ini murni hasrat pribadi yang selalu ingin bekerja dengan cepat dan tidak nyaman dengan mesin yang lemot (laptop kantor).

Ketika kantor tempat aku bekerja mengeluarkan kebijakan WFH, secara lahir batin aku dah siap. Terus terang, tanpa ada wabah Covid-19 pun aku sih pengennya bisa WFH secara rumah berada jauh di Lampung sana. Selain itu, aku merasa pekerjaan kantorku memang bisa dilakukan dari manapun asal ada koneksi internet.

Apakah sekarang aku WFH? Sayang sekali, otoritas yang mengelola perumahan tempat tinggalku di lampung melarang adanya keluar masuk dari perumahan sehingga bisa dipastikan aku ba gisa pulang ke Lampung. Akhirnya aku tidak bisa *Work From Home*, jadinya *Work From Kosan*. Bahasa Inggrisnya Kosan itu apa ya? *Dormitory* kah?

*Work From Dormitory*? Keren juga namanya....